"""empty message

Revision ID: 19c5a50bf799
Revises: 57654ecea803
Create Date: 2017-05-01 15:16:34.849300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c5a50bf799'
down_revision = '57654ecea803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist',
    sa.Column('itemid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('wish_url', sa.String(length=120), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('thumbnail_img', sa.NullType(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('itemid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist')
    # ### end Alembic commands ###
